/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Bean.Account;
import Bean.Employee;
import DAO.AccountDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author VIETTHI_PC
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    private Employee nv;
    private ThongTin tt;
    public DoiMatKhau(Employee nv, ThongTin tt) {
        this.nv = nv;
        this.tt = tt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hidePass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMoi = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtMoi2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtCu = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        setLocation(new java.awt.Point(775, 417));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hidePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_eye_24px.png"))); // NOI18N
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hidePassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassMousePressed(evt);
            }
        });
        jPanel1.add(hidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 30, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Mật khẩu cũ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 45, 115, 25));

        txtMoi.setText("Mật Khẩu Mật Khẩu");
        txtMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMoiMouseClicked(evt);
            }
        });
        jPanel1.add(txtMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 83, 187, 37));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu mới");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, 115, 25));

        txtMoi2.setText("Mật Khẩu Mật Khẩu");
        txtMoi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMoi2MouseClicked(evt);
            }
        });
        jPanel1.add(txtMoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 127, 187, 37));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nhập lại mật khẩu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, 125, 25));

        txtCu.setText("Mật Khẩu Mật Khẩu");
        txtCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCuMouseClicked(evt);
            }
        });
        jPanel1.add(txtCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 39, 187, 37));

        btnSubmit.setBackground(new java.awt.Color(46, 204, 113));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubmit.setText("Đổi mật khẩu");
        btnSubmit.setBorder(null);
        btnSubmit.setBorderPainted(false);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 182, 132, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean checkSamePass(String p1, String p2){
        return p1.equals(p2);
    }
    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked

        Account acc = AccountDAO.findAccount(nv.getEmployeeCode());
        String pass = String.valueOf(txtCu.getPassword());
        String moi = String.valueOf(txtMoi.getPassword());
        String moi2 = String.valueOf(txtMoi2.getPassword());
        if(pass.equals(acc.getPassWord())) {
        if(moi.equals(moi2)) {
            if (AccountDAO.changePass(nv.getEmployeeCode(), moi))
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        } else JOptionPane.showMessageDialog(this, "Sai mật khẩu hoặc mật khẩu mới không trùng khớp", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCuMouseClicked
        // TODO add your handling code here:
        txtCu.setEchoChar('*');
        if(txtCu.getText().equals("Mật Khẩu Mật Khẩu")) txtCu.setText("");
    }//GEN-LAST:event_txtCuMouseClicked

    private void txtMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMoiMouseClicked
        // TODO add your handling code here:
       txtMoi.setEchoChar('*');
        if(txtMoi.getText().equals("Mật Khẩu Mật Khẩu")) txtMoi.setText("");
    }//GEN-LAST:event_txtMoiMouseClicked

    private void txtMoi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMoi2MouseClicked
        // TODO add your handling code here:
        txtMoi2.setEchoChar('*');
        if(txtMoi2.getText().equals("Mật Khẩu Mật Khẩu")) txtMoi2.setText("");
    }//GEN-LAST:event_txtMoi2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // tt.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        tt.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void hidePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseExited
        // TODO add your handling code here:
        txtMoi.setEchoChar('*');
        txtMoi2.setEchoChar('*');
    }//GEN-LAST:event_hidePassMouseExited

    private void hidePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMousePressed
        // TODO add your handling code here:
        txtMoi.setEchoChar((char)0);
        txtMoi2.setEchoChar((char)0);
    }//GEN-LAST:event_hidePassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel hidePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtCu;
    private javax.swing.JPasswordField txtMoi;
    private javax.swing.JPasswordField txtMoi2;
    // End of variables declaration//GEN-END:variables
}
