/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Bean.Account;
import DAO.AccountDAO;
import thread.Clock;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author VIETTHI_PC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    static Date ad;
    public Login() {
        initComponents();
        password.setEchoChar((char) 0);
        Clock n = new Clock(clock);
        n.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        hidePass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JLabel();
        nity = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        ThongBaotxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quan Ly Khach San");
        setLocation(new java.awt.Point(600, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_hotel_building_120px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 160, 160));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 39)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("KHÁCH SẠN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 59));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 330, 0));

        hidePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_eye_24px.png"))); // NOI18N
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hidePassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePassMousePressed(evt);
            }
        });
        jPanel1.add(hidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_64px.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 63, -1, 74));

        username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        username.setText("Tài Khoản");
        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 77, 379, 43));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_password_64px_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 184, -1, -1));

        password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        password.setText("Mật Khẩu");
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 197, 379, 51));

        login.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_enter_52px.png"))); // NOI18N
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginMouseReleased(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 126, 65));

        nity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nity.setForeground(new java.awt.Color(255, 51, 0));
        nity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nity.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nityAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                nityAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(nity, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 328, 435, 54));

        clock.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        clock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clock.setText("20:22:30 AM");
        clock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                clockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 100, 40));

        ThongBaotxt.setForeground(new java.awt.Color(255, 51, 51));
        ThongBaotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ThongBaotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 400, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, -1, 550));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_52px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 13, -1, 41));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 39)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("QUẢN LÝ ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 59));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
       Account acc = AccountDAO.findAccount(username.getText());
        String pass = String.valueOf(password.getPassword());
        if (pass.equals(acc.getPassWord())) {
            System.out.println(AccountDAO.getPosition(username.getText()));
            if(AccountDAO.getPosition(username.getText()).equals("NV")) {
                EmployeeHome eh = new EmployeeHome(AccountDAO.getEmployeeNumBer(username.getText()));
                eh.setVisible(true);
                this.dispose();
            }
            if(AccountDAO.getPosition(username.getText()).equals("GD")) {
                GiamDocHome eh = new GiamDocHome(AccountDAO.getEmployeeNumBer(username.getText()));
                eh.setVisible(true);
                this.dispose();
            }
        }else ThongBaotxt.setText("TÀI KHOẢN KHÔNG CÓ HOẶC NHẬP SAI MẬT KHẨU");
// TODO add your handling code here:
    }//GEN-LAST:event_loginMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        if(username.getText().equals("Tài Khoản")) username.setText("");
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
       password.setEchoChar('*');
        if(password.getText().equals("Mật Khẩu")) password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void nityAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nityAncestorAdded

    }//GEN-LAST:event_nityAncestorAdded

    private void nityAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nityAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_nityAncestorMoved

    private void loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_loginMouseReleased

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
          login.setBackground(new Color(3,3,2));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
          login.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_loginMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void hidePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseExited
        // TODO add your handling code here:
        password.setEchoChar('*');
    }//GEN-LAST:event_hidePassMouseExited

    private void hidePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMousePressed
        // TODO add your handling code here:
         password.setEchoChar((char)0);
    }//GEN-LAST:event_hidePassMousePressed

    private void clockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_clockAncestorAdded
        // TODO add your handling code here
         
    }//GEN-LAST:event_clockAncestorAdded
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ThongBaotxt;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel hidePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nity;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
