/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Bean.Branch;
import Bean.Employee;
import DAO.BranchDAO;
import DAO.WarehouseDAO;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VIETTHI_PC
 */
public class WarehouseView extends javax.swing.JFrame {

    /**
     * Creates new form NhapKho
     */
    DefaultComboBoxModel branchName;
    private DefaultTableModel model;
    private List<Branch> listBranch;
    private Employee employee;

    public WarehouseView() {
        initComponents();
        setUI();
        setBranchCBB();
        showList();
    }

    public WarehouseView(Employee employee) {
        this.employee = employee;
        initComponents();

        setBranchCBB();
        setUI();
        showList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbChiNhanh = new javax.swing.JComboBox<>();
        btnDieuChinhGia = new javax.swing.JButton();
        btnNhapKho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết kho");

        jPanel1.setBackground(new java.awt.Color(179, 205, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTim.setText("Tìm kiếm sản phẩm");
        txtTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimMouseClicked(evt);
            }
        });
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKeyPressed(evt);
            }
        });
        jPanel1.add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 360, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_24px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TbSanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TbSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {"Mỳ tôm", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Mô tả"
            }
        ));
        TbSanPham.setFocusable(false);
        TbSanPham.setGridColor(new java.awt.Color(54, 54, 54));
        TbSanPham.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TbSanPham.setName(""); // NOI18N
        TbSanPham.setRowHeight(35);
        TbSanPham.getTableHeader().setReorderingAllowed(false);
        TbSanPham.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TbSanPhamFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TbSanPhamFocusLost(evt);
            }
        });
        TbSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TbSanPhamKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TbSanPhamKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TbSanPham);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 820, 516));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_52px.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        cbbChiNhanh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbChiNhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChiNhanhActionPerformed(evt);
            }
        });
        jPanel1.add(cbbChiNhanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 40));

        btnDieuChinhGia.setBackground(new java.awt.Color(46, 204, 113));
        btnDieuChinhGia.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnDieuChinhGia.setText("Điều chỉnh giá");
        btnDieuChinhGia.setBorder(null);
        btnDieuChinhGia.setBorderPainted(false);
        btnDieuChinhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDieuChinhGiaMouseClicked(evt);
            }
        });
        jPanel1.add(btnDieuChinhGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 120, 40));

        btnNhapKho.setBackground(new java.awt.Color(46, 204, 113));
        btnNhapKho.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnNhapKho.setText("Nhập kho");
        btnNhapKho.setBorder(null);
        btnNhapKho.setBorderPainted(false);
        btnNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapKhoMouseClicked(evt);
            }
        });
        jPanel1.add(btnNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setBranchCBB() {
        listBranch = BranchDAO.getListBranch();
        branchName = new DefaultComboBoxModel();
        for (int i = 0; i < listBranch.size(); i++) {
            branchName.addElement(listBranch.get(i));
        }
        cbbChiNhanh.setModel(branchName);
    }

    void setUI() {
        model = (DefaultTableModel) TbSanPham.getModel();
        if (employee.getPositionNumBer().equals("NV")) {
            cbbChiNhanh.setEnabled(false);
            int index;
            for (int i = 0; i < listBranch.size(); i++) {
                if (listBranch.get(i).getBranchCode() == employee.getBranchCode()) {
                    index = i;
                    cbbChiNhanh.setSelectedIndex(index);
                }
            }

        }
        if (employee.getPositionNumBer().equals("GD")) {
            btnNhapKho.hide();
        } else{
            btnDieuChinhGia.hide();
        }

        TbSanPham.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) TbSanPham.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        //   jTable1.getTableHeader().setOpaque(false);
        TbSanPham.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TbSanPham.getColumnModel().getColumn(0).setPreferredWidth(120);
        TbSanPham.getColumnModel().getColumn(1).setPreferredWidth(200);
        TbSanPham.getColumnModel().getColumn(2).setPreferredWidth(130);
        TbSanPham.getColumnModel().getColumn(3).setPreferredWidth(168);
        TbSanPham.getColumnModel().getColumn(4).setPreferredWidth(200);
    }

    public void showList() {
        model.setRowCount(0);
        List< Object> list = WarehouseDAO.listProduct(employee.getBranchCode());
        for (Object b : list) {
            model.addRow((Object[]) b);
        }
        model.setRowCount(list.size() + 13);
    }
    private void TbSanPhamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TbSanPhamFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TbSanPhamFocusGained

    private void TbSanPhamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TbSanPhamFocusLost
        // TODO add your handling code here:
        int x = TbSanPham.getSelectedColumn();
        int y = TbSanPham.getSelectedRow();
        System.out.println(TbSanPham.getValueAt(x, y));
    }//GEN-LAST:event_TbSanPhamFocusLost

    private void TbSanPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbSanPhamKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("ngu");
        }
    }//GEN-LAST:event_TbSanPhamKeyPressed

    private void TbSanPhamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TbSanPhamKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("ngu");
        }
    }//GEN-LAST:event_TbSanPhamKeyTyped

    private void txtTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimMouseClicked
        // TODO add your handling code here:
        if (txtTim.getText().equals("Tìm kiếm sản phẩm")) {
            txtTim.setText("");
        }
    }//GEN-LAST:event_txtTimMouseClicked

    private void txtTimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (!"".equals(txtTim.getText())) {
            Branch a = (Branch) cbbChiNhanh.getSelectedItem();
            List<Object> list = WarehouseDAO.findProduct(a.getBranchCode(), txtTim.getText());
            model.setRowCount(0);
            for (Object b : list) {
                model.addRow((Object[]) b);
            }
            model.setRowCount(list.size() + 13);

        } else {
            showList();
        }
    }//GEN-LAST:event_txtTimKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cbbChiNhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChiNhanhActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        Branch a = (Branch) cbbChiNhanh.getSelectedItem();
        List< Object> list = WarehouseDAO.listProduct(a.getBranchCode());
        for (Object b : list) {
            model.addRow((Object[]) b);
        }
    }//GEN-LAST:event_cbbChiNhanhActionPerformed

    private void btnNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapKhoMouseClicked
        // TODO add your handling code here:
        new NhapKho(employee, this).setVisible(true);
    }//GEN-LAST:event_btnNhapKhoMouseClicked

    private void btnDieuChinhGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDieuChinhGiaMouseClicked
        // TODO add your handling code here:
        int x = TbSanPham.getSelectedRow();
        int MSP = (int) TbSanPham.getValueAt(x, 0);
        if(x >= 0){
             new AdjustPriceView(this, MSP).setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm trước khi nhấn điều chỉnh!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }//GEN-LAST:event_btnDieuChinhGiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarehouseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarehouseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarehouseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarehouseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarehouseView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbSanPham;
    private javax.swing.JButton btnDieuChinhGia;
    private javax.swing.JButton btnNhapKho;
    private javax.swing.JComboBox<String> cbbChiNhanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
